repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.10"
    hooks:
      - id: ruff
        args: [--select, I, --fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v4.8.3"
    hooks:
      - id: commitizen
        stages: [commit-msg]
